# Generated by Django 4.1.7 on 2023-03-15 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerNews',
            fields=[
                ('news_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('by', models.CharField(max_length=100)),
                ('descendants', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=100)),
                ('kids', models.JSONField(null=True)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
